AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  positive-line-bot

Globals:
  Function:
    Timeout: 5

Resources:
  PositiveLineBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: positive-line-bot/
      Handler: positive-line-bot
      Runtime: go1.x
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /positive
            Method: GET
      Environment:
        Variables:
          # LINE_CHANNEL_SECRET: ''
          # LINE_CHANNEL_TOKEN: ''
          DYNAMODB_ENDPOINT: ''
          DYNAMODB_TABLE_NAME: 'PositiveLineBotTable'

  PositiveLineBotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'PositiveLineBotTable'
      AttributeDefinitions:
        - AttributeName: 'Id'
          AttributeType: 'N'
      KeySchema:
        - AttributeName: 'Id'
          KeyType: 'HASH'
      # ProvisionedThroughput:
      #   ReadCapacityUnits: '5'
      #   WriteCapacityUnits: '5'
      BillingMode: PAY_PER_REQUEST

Outputs:
  PositiveLineBotAPI:
    Description: 'API Gateway endpoint URL for Prod environment for PositiveLineBot'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/positive/'
  PositiveLineBotFunction:
    Description: 'PositiveLineBot Lambda Function ARN'
    Value: !GetAtt PositiveLineBotFunction.Arn
  PositiveLineBotFunctionIamRole:
    Description: 'Implicit IAM Role created for PositiveLineBot'
    Value: !GetAtt PositiveLineBotFunction.Arn
